png("plot3.png",width=480,height=480)
par(mfrow=c(1,1))
myTable<-read.table("household_power_consumption.txt",sep=";",header=T)
myTable1<-subset(myTable,Date=="1/2/2007" | Date=="2/2/2007")
date.Time<-strptime(paste(myTable1$Date,myTable1$Time),"%d/%m/%Y %H:%M:%S")
myTable2<-cbind(myTable1,date.Time)
plot(myTable2$date.Time,as.numeric(as.character(myTable2$Sub_metering_1)),type="l",col="black",xlab="",ylab="Energy sub metering")
lines(myTable2$date.Time,as.numeric(as.character(myTable2$Sub_metering_2)),type="l",col="red",xlab="",ylab="")
lines(myTable2$date.Time,as.numeric(as.character(myTable2$Sub_metering_3)),type="l",col="blue",ylab="",xlab="")
legend("topright",lty=1,col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.off()